# Generated by Django 5.2.14 on 2026-06-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('cardiologist', 'cardiologist'), ('dermatologist', 'dermatologist'), ('neurologist', 'neurologist')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('institution', models.CharField(max_length=100)),
                ('completed_appointments', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
