# Generated by Django 5.2.14 on 2026-06-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_appointment_patient_appointmentassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentassignment',
            unique_together={('appointments', 'doctor')},
        ),
    ]
