# Generated by Django 5.2.14 on 2026-06-02 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_alter_appointmentassignment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='termin',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='appointmentassignment',
            old_name='appointments',
            new_name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='responsible_doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='institution',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='scheduled', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='completed_appointments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentassignment',
            unique_together={('appointment', 'doctor')},
        ),
    ]
