# Generated by Django 5.2.14 on 2026-06-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_rename_termin_appointment_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptoms',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_status',
            new_name='status',
        ),
    ]
